spring.application.name=avis

# Configuration H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuration JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration H2 Console (pour développement)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration Spring Boot
server.port=8080

management.endpoints.web.exposure.include=beans,health,env,configprops

jwt.secret=avisAppSecretKeyTresLongueEtSecurisee1234567890ABCDEF
jwt.expiration=8640000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method